### ISSUE TITLE
SMH WTF are you doing project maker person. make a WASM version

### ISSUE THREAD

**Issue by Rstar284** [Rstar284/rpaste#4]
You Idiot @Rstar284.

**Comment by Rstar284** [comment]
To read: https://lib.rs/wasm
https://www.reddit.com/r/rust/comments/9d7u2n/using_wasmbindgen_with_rocket/
https://rustwasm.github.io/book/ or https://rustwasm.github.io/docs/book/

To ~~steal from~~ look at: https://github.com/snluu/lenote-mirror

Ideas:
Switch webserver from rocket.rs to actix.
Switch lang as a whole (extreme fallback)

**Comment by Rstar284** [comment]
Make sure you get it done *smh* dont procrastinate or i bonk you

**Comment by Rstar284** [comment]
Im switching framework to actix

**Comment by Rstar284** [comment]
Too much work. Am lazy, closing this now. lol.

**Comment by 13-05** [comment]
L
